name: Demo to create automatic PR

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "AUTHOR"  # Ignora cambios en `AUTHOR` para evitar loops infinitos
      - "timestamp.txt"  # Ignora cambios en `timestamp.txt` también

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:

      # ✅ 1. Verifica si el commit es de create-pull-request (evita loops)
      - name: Skip if PR from create-pull-request
        if: contains(github.event.head_commit.message, '[create-pull-request]')
        run: echo "Skipping workflow triggered by create-pull-request" && exit 0

      # ✅ 2. Verifica el código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # ✅ 3. Extrae datos del commit
      - name: Extract commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      # ✅ 4. Actualiza el archivo AUTHOR con el nombre del autor del commit
      - name: Update Author information
        run: echo "${{ env.GIT_COMMIT_AUTHOR_NAME }}" > AUTHOR

      # ✅ 5. Añade timestamp para forzar un cambio (siempre hay cambios nuevos)
      - name: Force Change to Trigger PR
        run: echo "$(date)" > timestamp.txt

      # ✅ 6. Añade TODOS los cambios al commit
      - name: Add all changes
        run: |
          git add .
          git commit -m "Update commit with all changes" || echo "No changes to commit"

      # ✅ 7. Verifica si hay cambios antes de continuar
      - name: Check for changes
        run: |
          git diff --quiet || echo "There are changes to commit" || exit 1

      # ✅ 8. Elimina la rama 'auto-pr-branch' si ya existe para evitar conflictos
      - name: Delete auto-pr-branch if it exists
        run: |
          git push origin --delete auto-pr-branch || echo "Branch does not exist, continuing..."

      # ✅ 9. Crea el Pull Request automático con los cambios
      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          branch-suffix: timestamp  # Agrega sufijo para evitar conflictos
          base: main
          title: "This is the title of the automatic PR"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: "This is the body of the automatic PR"
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true

      # ✅ 10. Habilita depuración para obtener más detalles en caso de errores
      - name: Enable Debug Mode (Optional)
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
