name: Demo to create automatic PR

on:
  push:
    branches:
      - "**"

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update Author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Check for changes
        run: |
          git diff --quiet || echo "There are changes to commit" || exit 1

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch1"
          branch-suffix: timestamp
          base: main
          title: "This is the title of the automatic PR"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: "This is the body of the automatic PR"
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true

